
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: env("postgresql://neondb_owner:dzyF6icoCXv0@ep-green-river-a5ibu88r.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"),
  },
});
